_target_: src.models.realnvp_module.RealNVPLitModule
net:
  _target_: src.models.realnvp.realnvp.RealNVP_2D
  masks:
    - [1.0, 0.0]
    - [0.0, 1.0]
    - [1.0, 0.0]
    - [0.0, 1.0]
    - [1.0, 0.0]
    - [0.0, 1.0]
    - [1.0, 0.0]
    - [0.0, 1.0]
  hidden_dim: 128

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler: null